import type { Metadata } from "next";
import "./globals.css";
import { BiBrightness } from "react-icons/bi";
import Link from "next/link";
import CreateButton from "@/app/components/createbtn";

export const metadata: Metadata = {
   title: "Product Store",
   // description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="select-none bg-slate-900">
            <header>
               <nav className="mb-5 flex h-16 items-center justify-between px-3 py-7 outline outline-1 outline-slate-600 sm:px-7 sm:py-10">
                  <Link href={"/"}>
                     <h1 className="bg-gradient-to-r from-teal-600 to-blue-600 bg-clip-text text-2xl font-bold text-transparent sm:text-3xl">
                        Product Store🛒
                     </h1>
                  </Link>

                  <div className="flex items-center justify-center gap-4 text-slate-200">
                     <CreateButton />
                     <button className="aspect-square rounded-md bg-slate-800 p-1 outline-2 transition-transform hover:outline hover:outline-blue-500 active:scale-95 sm:p-2">
                        <BiBrightness className="m-auto size-7" />
                     </button>
                  </div>
               </nav>
            </header>
            <main className="px-5 pb-5 sm:px-20">{children}</main>
         </body>
      </html>
   );
}
