import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import CreateButton from "@/app/components/createbtn";
import ThemeButton from "./components/themebtn";

export const metadata: Metadata = {
   title: "Product Store",
   // description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="select-none bg-background">
            <header>
               <nav className="mb-5 flex h-16 items-center justify-between px-3 py-7 outline outline-1 outline-slate-600 sm:px-7 sm:py-10">
                  <Link href={"/"}>
                     <h1 className="bg-gradient-to-r from-teal-600 to-blue-600 bg-clip-text text-2xl font-bold text-transparent sm:text-3xl">
                        Product Store🛒
                     </h1>
                  </Link>

                  <div className="text-textclr flex items-center justify-center gap-4">
                     <CreateButton />
                     <ThemeButton />
                  </div>
               </nav>
            </header>
            <main className="px-5 pb-5 sm:px-20">{children}</main>
         </body>
      </html>
   );
}
